# render.yaml

services:
  - name: web
    type: web
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      NODE_ENV: production
    routes:
      - path: "/https://population-census-backend.onrender.com*"
